### ISSUE TITLE
Organize the assets under /assets

### ISSUE THREAD

**Issue by valenotary** [Doggphin/geoengine#2]
PLEASE GOD STOP MIXING THE SOURCE AND ASSET FILES
ANY NON SOURCE FILE SHOULD JUST BE UNDER `/assets`
BONUS POINTS IF THERE ARE SUB FOLDERS FOR EACH ASSET TYPE

ALSO MAYBE TRY NOT TO INCLUDE ANY HUGE GLTF FILES

**Comment by doggphin** [comment]
👍
